### ISSUE TITLE
wiki user agent and rate limiting

### ISSUE THREAD

**Issue by nobbyfix** [KyouinDev/j-azur-lane#1]
Wanted to let you know that you don't have to use a fake browser user agent to connect to the wiki. As long as you limit yourself to 1 requests every 5 seconds (as per the sites robots.txt) you are fine and won't get blocked/banned.

**Comment by KyouinDev** [comment]
Nice to know!
Anyway, why 1 request every 5 seconds, doesn't it say 1? Which robots.txt are you referring to?

**Comment by nobbyfix** [comment]
You're right, its 1 per second, it got changed 3 months ago from 5 and i hadn't checked it in that timeframe.

**Comment by KyouinDev** [comment]
Oh, I see... By the way, I can't remove user-agent, for they've done the wiki structure, it'd load page on mobile mode and things like that, I just force it to prevent from happening.
